using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DiagnosticSystemWeb.DLL;

namespace DiagnosticSystemWeb.Models
{
    public class Patient
    {

        public int Id { get; set; }
        public string PatientName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string MobileNo { get; set; }
        public int TestId { get; set; }
        public string BillNumber { get; set; }
        public decimal DueAmount { get; set; }
        public DateTime DueDate { get; set; }
        static long num = 1;
        public string AutoGeneratedBillNo()
        {
            DateTime nowtime = DateTime.Now;
            string myDate = GetUniqueNumberAsPerDate(nowtime);
            return BillNumber = myDate;
        }
        public string GetUniqueNumberAsPerDate(DateTime date)
        {
            double dateStr = date.ToOADate();
            dateStr *= 10000;
            long alwaysIncrementeduniqueNum = num + 1;
            string uniqueNumber = alwaysIncrementeduniqueNum + " " + dateStr;
            string newuniqueNumber = uniqueNumber.Replace(".", "");
            string final = newuniqueNumber.Replace(" ", "");
            return final;
        }
    }
}